# 全局日期处理
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
# 性能优化重要参数需要结合 linux服务器参数：net.core.somaxconn 做优化 （accept-queue（全连接队列））
server.tomcat.accept-count=200
# 优雅关机
server.shutdown=GRACEFUL
# 默认 30s
spring.lifecycle.timeout-per-shutdown-phase=40s